### ISSUE TITLE
We lack texlive

### ISSUE THREAD

**Issue by somas95** [flathub/de.wolfvollprecht.UberWriter#1]

**Comment by somas95** [comment]
bot, build de.wolfvollprecht.UberWriter.Plugin.TexLive

**Comment by TingPing** [comment]
A new repo has to be made for every plugin.

**Comment by TingPing** [comment]
First lets get it actually buildable: https://flathub.org/builds/#/builders/24/builds/177

Looks like your branch is wrong.
