### ISSUE TITLE
Update runtime

### ISSUE THREAD

**Issue by Eonfge** [flathub/de.wolfvollprecht.UberWriter#11]
You're current runtime is GNOME 3.32, which is as of today end-of-life. Could you update it to a more recent version?

**Comment by somas95** [comment]
Precisely yesterday I updated the beta branch, I have plans to make a release next week b6f312d1a234f6229eed2a61780a8d3e2635cd9d

**Comment by nyx-lyb3ra** [comment]
Any news on this?

**Comment by somas95** [comment]
I wanted to make a release yesterday, when I found a serious regression. If at the end of this day I didn't solved it, I'll upgrade the runtime regardless of the main update
