### ISSUE TITLE
Screenshots are not shown on flathub

### ISSUE THREAD

**Issue by somas95** [flathub/de.wolfvollprecht.UberWriter#2]
@jgarciao I was told to ping you. The issue is just what the tittle says... Gnome software shows the preview thumbnails, but it also lacks the "big" screenshots. Flathub doesn't show neither one

**Comment by jgarciao** [comment]
Its not a problem in the website or gnome-software. There there is some kind of problem with the conversion from the screenshots provided in your appdata.xml file and the ones that are in the web server:
 
In your appdata they look fine:
- https://user-images.githubusercontent.com/8913975/39668442-37ec83b8-50ce-11e8-9896-0d2f5876ebfb.png
- https://user-images.githubusercontent.com/8913975/39668440-379c4236-50ce-11e8-8c89-3d03c639953e.png
- https://user-images.githubusercontent.com/8913975/39668443-380813f8-50ce-11e8-8bc1-b69f97fb6080.png
- https://user-images.githubusercontent.com/8913975/39668438-375ffbb4-50ce-11e8-8abe-1109702f8656.png

This is what is in the web server (all grey images):

https://flathub.org/api/v1/apps/de.wolfvollprecht.UberWriter


screenshots |  
-- | --
0 |  
thumbUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/224x126/de.wolfvollprecht.UberWriter-31ee6a7fb19d182c24ec79339f8ee767.png"
imgMobileUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/624x351/de.wolfvollprecht.UberWriter-31ee6a7fb19d182c24ec79339f8ee767.png"
imgDesktopUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/752x423/de.wolfvollprecht.UberWriter-31ee6a7fb19d182c24ec79339f8ee767.png"
1 |  
thumbUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/224x126/de.wolfvollprecht.UberWriter-d459b316d5398d07ebd5dbb3f9df56b1.png"
imgMobileUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/624x351/de.wolfvollprecht.UberWriter-d459b316d5398d07ebd5dbb3f9df56b1.png"
imgDesktopUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/752x423/de.wolfvollprecht.UberWriter-d459b316d5398d07ebd5dbb3f9df56b1.png"
2 |  
thumbUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/224x126/de.wolfvollprecht.UberWriter-547650cbf9566dce185657f311d31488.png"
imgMobileUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/624x351/de.wolfvollprecht.UberWriter-547650cbf9566dce185657f311d31488.png"
imgDesktopUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/752x423/de.wolfvollprecht.UberWriter-547650cbf9566dce185657f311d31488.png"
3 |  
thumbUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/224x126/de.wolfvollprecht.UberWriter-6a103dc6f23cd6e72a0b4b0db92f5375.png"
imgMobileUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/624x351/de.wolfvollprecht.UberWriter-6a103dc6f23cd6e72a0b4b0db92f5375.png"
imgDesktopUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/752x423/de.wolfvollprecht.UberWriter-6a103dc6f23cd6e72a0b4b0db92f5375.png"
4 |  
thumbUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/224x126/de.wolfvollprecht.UberWriter-98bd0dfb6f775b2f2c68b436cb1af846.png"
imgMobileUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/624x351/de.wolfvollprecht.UberWriter-98bd0dfb6f775b2f2c68b436cb1af846.png"
imgDesktopUrl | "https://flathub.org/repo/screenshots/de.wolfvollprecht.UberWriter-stable/752x423/de.wolfvollprecht.UberWriter-98bd0dfb6f775b2f2c68b436cb1af846.png"


Maybe changing the screenshots url for raw.githubusercontent.../... will work better, but I guess @TingPing  or @nedrichards can know better what is happening.

**Comment by somas95** [comment]
Let's try 1e04194ecad9fcabf34da6d8fc8dc60b0bcae4ed

**Comment by jgarciao** [comment]
Try like this if if doesn't work:
https://raw.githubusercontent.com/UberWriter/uberwriter/master/screenshots/main.png

**Comment by somas95** [comment]
What's the maximum delay between a successful build and the web showing all
the updated metadata?

**Comment by somas95** [comment]
Still doesn't work

**Comment by somas95** [comment]
@jgarciao do you think it's a problem with the server or with the images?

**Comment by wolfv** [comment]
@jgarciao @somas95 should we try hosting the images on some external service like `imgur` or a custom domain? 
Could it be related to https? Or related to the images being PNG? (we could try JPG even though it doesn't make a lot of sense for screenshots).

**Comment by somas95** [comment]
I thought on hosting the images on my hosting, but I also use https...It doesn't make sense to me that there ir a issue with that, since almost every site nowadays use it. 
Here the issue seems to be the image size: https://github.com/flathub/linux-store-frontend/issues/59
So maybe it's something related with the image properties

**Comment by jgarciao** [comment]
I'm sorry to read that it's not working yet. I've looked at the qt demo flatpak app and the [appstream screenshots entry also uses images hosted at github the same way](https://github.com/flatpak/qt-flatpak-demo/blob/master/org.flatpak.qtdemo.appdata.xml)

```
<screenshots>
    <screenshot type="default">
      <image type="source">https://raw.githubusercontent.com/flatpak/qt-flatpak-demo/master/assets/screenshot.png</image>
    </screenshot>
</screenshots>
```

The difference I see is that you also specify the `<caption>` tag. I don't remember any other app declaring this, although[ is in the spec.](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) Could you try to remove it?

**Comment by somas95** [comment]
Let's try that

**Comment by jgarciao** [comment]
@nedrichards The screenshots are still not showing up properly. They are in the server but the images are all grey. I remember once we found a problem with another app and the solution was to clean some build cache? Could you help us with this?

**Comment by wolfv** [comment]
@nedrichards any help would be greatly appreciated as I would really like to "make some noise" on twitter that uberwriter is back :)

**Comment by nedrichards** [comment]
I've run the appstream-util command locally on the current file and that generated screenshots that were perfectly fine visually - however they're too small. I don't get anything larger than 752x423. Empty folders for 1248x702 and 1504x846 - this is the same as the issue referred to above. https://github.com/flathub/linux-store-frontend/issues/59

Tto reproduce locally I dropped into a GNOME SDK container with:

> flatpak run --command=bash --filesystem=home --share=network org.gnome.Sdk//3.28

and ran:

> appstream-util mirror-screenshots de.wolfvollprecht.UberWriter.xml . .

**Comment by somas95** [comment]
Maybe what is happening is that despite our images having a width greater than the required 620px, when scaled to fit the 16:9 ratio the width is cropped under the minimum width required. I'll redo the screenshots today

**Comment by somas95** [comment]
Now works like a charm. Thanks!
