### ISSUE TITLE
Store page is corrupt

### ISSUE THREAD

**Issue by somas95** [flathub/de.wolfvollprecht.UberWriter#5]
Both data and metadata are not shown in the Flathub page, except for the logo and description
The appdata.cml file is valid, running appstream-validate relax on it returns an OK status, without prompting any issues
I waited a little in case it was a cache issue, but it doesn't seems to be.

**Comment by somas95** [comment]
Btw, @TingPing, were do belong this kind of issues, in the repository of the app or on the repository of linux-store-frontend?

**Comment by TingPing** [comment]
*Usually* the app is the correct place because it is missing data. Sometimes its a website bug though.

**Comment by somas95** [comment]
Thanks! Also, is there a  way to try to reproduce this kind of issues (erros generating the website)? As appstream-validate doesn't say anything, trying to fix it blindly, forcing big recompilation times and meaningless updates for our users doesn't seem the way to go

**Comment by TingPing** [comment]
Not that I know of. It is a bit of a pain to debug.

**Comment by somas95** [comment]
@TingPing any hint here? I'd like to have working images when we release the next version, but I don't get what I'm doing wrong in the appdata
