### ISSUE TITLE
unreasonable access

### ISSUE THREAD

**Issue by ghost** [flathub/de.wolfvollprecht.UberWriter#6]
Thanks for making this programm available via flathub. 

however, I wonder why a simple markdown editor should have access to both network and whole filesystem?

suggestion:
remove "--share=network" from the manifest
replace "--filesystem=host" with "--filesystem=home"

**Comment by somas95** [comment]
Actually we use mathjs from a cdn to render latex on the preview mode, hence the network access.
The --filesystem=host could be changed, tho. I'll test that the change doesn't break anything...

**Comment by ghost** [comment]
thanks for the clarification!

**Comment by somas95** [comment]
Also, now that I remember we get the definitions from the Internet too (yes, if you ctrl + click on a word you'll get a dictionary entry for that word :p )
