### ISSUE TITLE
High CPU consumption on Manjaro Xfce

### ISSUE THREAD

**Issue by nam1962** [flathub/de.wolfvollprecht.UberWriter#8]
Thank for reviving this excellent editor and making it available on flathub.

Small problem : it consumes an enormous amount of CPU on my Manjaro Xfce stable.

I also tried the uberwriter-git on AUR, but this one doesn't start.

[edit] I tried the uberwriter on AUR, this one is running without CPU consumption.
It makes the flathub packaging possible culprit !

**Comment by somas95** [comment]
Hi! Sorry for the delay, I don't know why I was not notified by this. With the flatpak package, could you try to disable the scroll gradient? That does the trick for some users
